# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Intranet of Stuff
email: tcjennings@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
   One man's quest to add smart to dumb through home automation,
   coding, and throwing good money after bad. I don't know if steady-state
   if achievable, but I'll die trying. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.intranetofstuff.com"
twitter_username: tcjennings
github_username: tcjennings
reddit_username: intranetofstuff
collections_dir: collections
collections:
    first_principles:
       output: true
       title: First Principles
    use_cases:
       output: true
       title: Use Cases
    the_tools:
       output: true
       title: The Tools
    the_house:
       output: true
       title: The House
    the_erv:
       output: true
       title: The ERV
    the_network:
       output: true
       title: The Network
    elk_stack:
       output: true
       title: The ELK Stack
    hue:
       output: true
       title: Hue Lighting
    netatmo:
       output: true
       title: NetAtmo
    smart_bed:
       output: true
       title: Smart Bed
    smartthings:
       output: true
       title: Samsung SmartThings
    thermostat:
       output: true
       title: Smart Thermostat
    raspberry_pi:
       output: true
       title: Raspberry Pi and Arduino
# Build settings
markdown: kramdown
google_analytics: UA-79513490-1

